const { e } = require("./vars.json");

module.exports = {
    eightball_answers: [
        `absolutlie, of cuors!! ${e.happy.e}`, `noe.. not at alle.. ${e.sad.e}`,
        `honestlie... ${e.angel.e} i hav no ideae ${e.sad.e}`,
        `dat's obviouslie a noe ${e.sad.e}`,
        `i thinke soe.. ${e.think.e}`,
        `i dont think soe ${e.sad.e}`, `obviouslie ${e.glad.e}`,
        `i'm not suar ${e.think.e}`,
        `hard to answere ${e.sad2.e}`,
        `i'm 100% certaine, yese!! ${e.excited.e}`,
        `how am i supoesd to giv an anser to dat ${e.think.e}`,
        `maybi!! ${e.glad.e}`, `wat da hekke? NOE!! ${e.angry_pink.e}`,
        `dis question doesnt maek sens ${e.think.e}`,
        `maybi ${e.think.e}`, `noe.. ${e.sad.e}`,
        `i dont wana tel yu ${e.silly.e}`,
        `of cuors!! ${e.happy.e}`, `yeahe ${e.glad.e}`,
        `i dubt it ${e.sad.e}`,
        `da rng says yese! ${e.glad.e}`
    ],
    pick_answers: [
        `${e.think.e} i picke {i}! ${e.happy.e}`,
        `${e.think.e} i choos {i}! ${e.happy.e}`,
        `${e.angel.e} honestlie... i prefere {i}! ${e.think.e}`,
        `${e.happy.e} i think {i} is de best wan`,
        `${e.think.e} my gut tels me to goe wit {i}!!`,
        `after som hevi thinking... ${e.think.e} i gues i choos {i}!!`,
        `my opinion might be biased but {i} is de best wan!! ${e.business.e}`,
        `ar yu dum?? ${e.silly.e} cant yu alredi see dat {i} is de onli gud wan?? ${e.sad.e}`,
        `${e.sad.e} i dont liek eny option but i gues {i} is de best wan`,
        `${e.really.e} ar yu chalenging me?? whu wuldnte pick {i}???`
    ],
    permission_denied_answers: [
        `${e.sad2.e} i dont wana!!`,
        `noe!! ${e.sad.e}`,
        `NOE!! ${e.angry_pink.e}`,
        `my ownere told me not to ${e.stare.e}`,
        `i cant do dat ${e.sad.e}`,
        `let me sleepe!! ${e.sleep.e}`,
        `i wil onli doe wat i want to. and dat is not on da list. ${e.angry_pink.e}`,
        `its very harde to execut dat comande ${e.clenched_teeth_angry.e}`,
        `let me checke.. ${e.read.e} yu arn't permited to do dat!! ${e.clenched_teeth_angry.e}`,
        `leev me aloen ${e.disgust.e}`,
        `i wana ski!! ${e.ski.e}`,
        `if yu trie to do dat againe i wil lik yur eyes!! ${e.mad.e}${e.tongue_down.e}`,
        `go lik yur feet ${e.tongue_left.e}🦶`,
        `do yu reali think yu can do dat ${e.think.e}`,
        `i'm not gona do dat.. ${e.sad.e}`,
        `stop disturbinge me ${e.sad.e}`,
        `i'm reeding!! cant yu see!! ${e.read.e}`,
        `yu'r not mi owner! ${e.angry_pink.e}`,
        `yu dont get to decied wat i do ${e.disgust.e}`,
        `i'm at a partie! ${e.party.e} can't do yur comande! ${e.silly.e}${e.whistling.e}`,
        `i'm gona hamer yur hed for being so anoyinge <:hammering:762814921616392192>${e.sad.e}`,
        `helo !! yu waned to do dis comande riet ?? wel ${e.silly.e} too bad i dont wana doe it <:funny:717690391499112508>`,
        `${e.mad.e} i told yu not to !!`,
        `<:oops:729386039474520159> i acidentali aet da comand, so i cant doe it ${e.sad.e}`,
        `if i doo dis comand, yu'r gona die in a tragik car acident !! ${e.sad.e}`,
        `yese!! ${e.happy.e} i'm gona do dat comand... ${e.happy.e} wehnever yu get premisions yu garragabuga ${e.mad.e}`,
        `i acidentali died so i cant do da comand ${e.sad.e}${e.silly.e}`,
        `ask da oogi boogi gods ${e.angel.e}${e.tribaldance.e}`,
        `why do yu even trie ${e.sad3.e} im disapointed at yu !!1!`,
        `i am buzy !! ${e.hammering.e}`,
        `chek yur rols ${e.really.e}`,
        `i wil do it wans 1+1 = 3 !! ${e.stare.e}`,
        `stop tryin ${e.please.e}`,
        `busi listening to my bot frends ${e.whistling.e}`,
        `go do somthin moar productiv dan bothering me ${e.tongue_left.e}`,
        `i dont feel liek doing dat comeand righte nowe honestli ${e.think.e}`,
        `ar yu proud of yurself for anoying me?? ${e.angry_pink.e}`,
        `${e.stare.e} cant execut this comand withuot inspecting yu !! ${e.read.e}`,
        `meybi wans yur alowd to do dis comand yu can com bak and execut it ${e.really.e}`,
        `im out of ideas !! just stope !! ${e.sad3.e} yur meking me sade...`
    ]
}